logo: Minimalist blog
website_bio: Minimalist blog theme is liteweight and work with lume. 
author:
  name: Rajdeep Singh,
  email: officialrajdeepsingh@gmail.com,
  url: https://officialrajdeepsingh.dev/pages/about/
